/**
 * Build llms.txt / llms-full.txt catalogs from the public marketing route registry.
 * Regenerated by `npm run llms:generate` (also runs on prebuild).
 */
import {getAboutCopy} from "@/lib/marketing/about-landing-content";
import {getContactCopy} from "@/lib/marketing/contact-landing-content";
import {getHomepageCopy} from "@/lib/marketing/homepage-content";
import {
  getCookiesDoc,
  getPrivacyDoc,
  getTermsDoc,
} from "@/lib/marketing/legal-landing-content";
import {SEO_TOOL_LANDING_COPY} from "@/lib/marketing/seo-tool-landing-copy";
import {TOOL_LANDING_COPY} from "@/lib/marketing/tool-landing-copy";
import {
  getToolLanding,
  listSitemapPaths,
} from "@/lib/marketing/tool-landing-registry";
import {listPublishedDocs} from "@/server/marketing/docs-data";

export type LlmsLink = {
  path: string;
  title: string;
  description: string;
  section: LlmsSection;
};

export type LlmsSection =
  | "Home"
  | "Image tools"
  | "SEO landing pages"
  | "Bulk tools"
  | "Docs"
  | "Company";

const PRIVATE_PREFIXES = ["/api", "/dashboard", "/account", "/admin", "/login", "/register"];

const GENERIC_TOOL_PATHS = new Set([
  "/compress-image",
  "/resize-image",
  "/crop-image",
  "/convert-image",
  "/rotate-image",
  "/watermark-image",
  "/blur-region",
  "/meme-generator",
  "/geotag-image",
  "/image-metadata",
  "/image-metadata-editor",
  "/bulk-image-tools",
]);

const BULK_PATHS = new Set(["/bulk-compress", "/bulk-resize", "/bulk-convert"]);

const COMPANY_PATHS = new Set([
  "/pricing",
  "/privacy",
  "/terms",
  "/cookies",
  "/about",
  "/contact",
  "/search",
]);

function stripOrigin(url: string): string {
  return url.replace(/\/$/, "");
}

function absolute(origin: string, path: string): string {
  if (path === "/") return stripOrigin(origin) + "/";
  return `${stripOrigin(origin)}${path.startsWith("/") ? path : `/${path}`}`;
}

function isPrivatePath(path: string): boolean {
  return PRIVATE_PREFIXES.some((prefix) => path === prefix || path.startsWith(`${prefix}/`));
}

function sectionForPath(path: string): LlmsSection {
  if (path === "/") return "Home";
  if (path === "/docs" || path.startsWith("/docs/")) return "Docs";
  if (COMPANY_PATHS.has(path)) return "Company";
  if (BULK_PATHS.has(path)) return "Bulk tools";
  if (GENERIC_TOOL_PATHS.has(path)) return "Image tools";
  return "SEO landing pages";
}

function sitePageEntry(path: string): LlmsLink | null {
  switch (path) {
    case "/": {
      const copy = getHomepageCopy("en");
      return {
        path,
        title: "Homepage",
        description: copy.metaDescription,
        section: "Home",
      };
    }
    case "/pricing":
      return {
        path,
        title: "Pricing",
        description:
          "Compare Img Pilot Guest, Free and Pro plans, processing limits, bulk capacity and paid checkout availability.",
        section: "Company",
      };
    case "/docs":
      return {
        path,
        title: "Documentation",
        description:
          "Guides for the Img Pilot API, webhooks, CMS integrations, AI batches, automation and collaboration.",
        section: "Docs",
      };
    case "/privacy": {
      const doc = getPrivacyDoc("en");
      return {
        path,
        title: doc.hero.h1,
        description: doc.metaDescription,
        section: "Company",
      };
    }
    case "/terms": {
      const doc = getTermsDoc("en");
      return {
        path,
        title: doc.hero.h1,
        description: doc.metaDescription,
        section: "Company",
      };
    }
    case "/cookies": {
      const doc = getCookiesDoc("en");
      return {
        path,
        title: doc.hero.h1,
        description: doc.metaDescription,
        section: "Company",
      };
    }
    case "/about": {
      const copy = getAboutCopy("en");
      return {
        path,
        title: "About",
        description: copy.metaDescription,
        section: "Company",
      };
    }
    case "/contact": {
      const copy = getContactCopy("en");
      return {
        path,
        title: "Contact",
        description: copy.metaDescription,
        section: "Company",
      };
    }
    case "/search":
      return {
        path,
        title: "Search tools",
        description: "Find Img Pilot image tools with filters and popular suggestions.",
        section: "Company",
      };
    default:
      return null;
  }
}

export function resolveLlmsLink(path: string): LlmsLink {
  if (isPrivatePath(path)) {
    throw new Error(`Refusing private path in llms catalog: ${path}`);
  }

  const site = sitePageEntry(path);
  if (site) return site;

  const toolCopy = TOOL_LANDING_COPY[path];
  if (toolCopy) {
    return {
      path,
      title: toolCopy.h1,
      description: toolCopy.metaDescription,
      section: sectionForPath(path),
    };
  }

  const seoCopy = SEO_TOOL_LANDING_COPY[path];
  if (seoCopy) {
    return {
      path,
      title: seoCopy.h1,
      description: seoCopy.metaDescription,
      section: sectionForPath(path),
    };
  }

  const slug = path.replace(/^\//, "");
  const landing = getToolLanding(slug);
  if (landing && !landing.redirectTo) {
    return {
      path,
      title: landing.h1,
      description: landing.description,
      section: sectionForPath(path),
    };
  }

  const doc = listPublishedDocs().find((item) => item.path === path);
  if (doc) {
    return {
      path: doc.path,
      title: doc.title,
      description: doc.description,
      section: "Docs",
    };
  }

  throw new Error(`No llms.txt description for public path: ${path}`);
}

/** Public indexable marketing paths + published docs articles (no private app routes). */
export function listLlmsLinks(): LlmsLink[] {
  const paths = new Set<string>(listSitemapPaths());
  for (const doc of listPublishedDocs()) {
    paths.add(doc.path);
  }

  const links: LlmsLink[] = [];
  for (const path of [...paths].sort((a, b) => a.localeCompare(b))) {
    if (isPrivatePath(path)) continue;
    links.push(resolveLlmsLink(path));
  }
  return links;
}

function renderSection(
  origin: string,
  heading: string,
  links: LlmsLink[],
): string {
  if (links.length === 0) return "";
  const lines = [`## ${heading}`, ""];
  for (const link of links) {
    lines.push(`- [${link.title}](${absolute(origin, link.path)}): ${link.description}`);
  }
  lines.push("");
  return lines.join("\n");
}

const SECTION_ORDER: LlmsSection[] = [
  "Home",
  "Image tools",
  "Bulk tools",
  "SEO landing pages",
  "Docs",
  "Company",
];

export function renderLlmsTxt(origin: string): string {
  const links = listLlmsLinks();
  const home = links.find((l) => l.path === "/");
  const tools = links.filter((l) => l.section === "Image tools" || l.section === "Bulk tools");
  const companyCore = links.filter((l) =>
    ["/pricing", "/docs", "/privacy", "/terms", "/contact"].includes(l.path),
  );
  const featuredLandings = links
    .filter((l) => l.section === "SEO landing pages")
    .slice(0, 12);

  const parts = [
    "# Img Pilot",
    "",
    `> ${home?.description ?? "Private online tools for compressing, resizing, converting and optimizing images."}`,
    "",
    "Img Pilot provides guest-friendly image tools with private temporary storage and automatic cleanup. Dashboard, admin, account and API endpoints are intentionally omitted from this file.",
    "",
    `For the complete public URL list, see [llms-full.txt](${absolute(origin, "/llms-full.txt")}).`,
    "",
    renderSection(origin, "Home", links.filter((l) => l.path === "/")),
    renderSection(origin, "Image tools", tools),
    renderSection(origin, "Highlighted SEO landings", featuredLandings),
    renderSection(origin, "Docs & company", companyCore),
  ];

  return parts.filter(Boolean).join("\n").trimEnd() + "\n";
}

export function renderLlmsFullTxt(origin: string): string {
  const links = listLlmsLinks();
  const home = links.find((l) => l.path === "/");
  const parts = [
    "# Img Pilot — full public page index",
    "",
    `> ${home?.description ?? "Complete catalog of indexable public Img Pilot pages for LLM crawlers."}`,
    "",
    "Generated from `listSitemapPaths()` plus published documentation articles. Excludes `/api`, `/dashboard`, `/account` and `/admin`.",
    "",
    `Summary file: [llms.txt](${absolute(origin, "/llms.txt")}).`,
    "",
  ];

  for (const section of SECTION_ORDER) {
    parts.push(renderSection(origin, section, links.filter((l) => l.section === section)));
  }

  return parts.filter(Boolean).join("\n").trimEnd() + "\n";
}

export function resolveLlmsOrigin(envOrigin?: string): string {
  const raw = (envOrigin ?? process.env.NEXT_PUBLIC_APP_URL ?? "https://imgpilot.com").trim();
  try {
    return stripOrigin(new URL(raw).origin);
  } catch {
    return "https://imgpilot.com";
  }
}
