/** Stable guest API error codes — never invent route-local messages. */

export type SafeGuestErrorCode =
  | "INVALID_REQUEST"
  | "GUEST_SESSION_ACCESS_DENIED"
  | "GUEST_SESSION_EXPIRED"
  | "GUEST_LIMIT_REACHED"
  | "GUEST_ACTIVE_JOB_EXISTS"
  | "STORAGE_NOT_CONFIGURED"
  | "STORAGE_UNAVAILABLE"
  | "OBJECT_NOT_FOUND"
  | "OBJECT_TOO_LARGE"
  | "OBJECT_SIZE_MISMATCH"
  | "UNSUPPORTED_MEDIA_TYPE"
  | "VALIDATION_FAILED"
  | "CORRUPT_IMAGE"
  | "JOB_NOT_FOUND"
  | "JOB_NOT_READY"
  | "OPERATION_NOT_SUPPORTED"
  | "GUEST_AI_NOT_CONFIGURED"
  | "GUEST_AI_TIMEOUT"
  | "GUEST_AI_RATE_LIMITED"
  | "GUEST_AI_PROVIDER_UNAVAILABLE"
  | "GUEST_AI_RESPONSE_INVALID"
  | "GUEST_METADATA_EDITOR_SOURCE_NOT_READY"
  | "GUEST_METADATA_EDITOR_SOURCE_EXPIRED"
  | "GUEST_METADATA_EDITOR_DRAFT_INVALID"
  | "GUEST_METADATA_EDITOR_FIELD_TOO_LONG"
  | "GUEST_METADATA_EDITOR_FILENAME_INVALID"
  | "GUEST_METADATA_EDITOR_KEYWORDS_INVALID"
  | "GUEST_METADATA_EDITOR_AI_RESULT_NOT_FOUND"
  | "GUEST_METADATA_EDITOR_AI_RESULT_NOT_ALLOWED"
  | "GUEST_METADATA_EDITOR_EXPORT_FAILED"
  | "GUEST_METADATA_EDITOR_RENAMED_DOWNLOAD_FAILED"
  | "GUEST_METADATA_EDITOR_RATE_LIMITED"
  | "GUEST_BULK_LIMIT"
  | "GUEST_BULK_TOO_MANY_FILES"
  | "GUEST_BULK_BATCH_TOO_LARGE"
  | "GUEST_BULK_ACTIVE_EXISTS"
  | "GUEST_BULK_NOT_READY"
  | "GUEST_BULK_ZIP_FAILED"
  | "GUEST_BULK_ZIP_TOO_LARGE"
  | "GUEST_BULK_FEATURE_REQUIRED"
  | "INTERNAL_ERROR";

export class GuestDomainError extends Error {
  readonly code: SafeGuestErrorCode;

  constructor(code: SafeGuestErrorCode, message?: string) {
    super(message ?? code);
    this.name = "GuestDomainError";
    this.code = code;
  }
}

export function httpStatusForGuestError(code: SafeGuestErrorCode): number {
  switch (code) {
    case "GUEST_SESSION_ACCESS_DENIED":
      return 403;
    case "GUEST_SESSION_EXPIRED":
      return 401;
    case "GUEST_LIMIT_REACHED":
    case "GUEST_ACTIVE_JOB_EXISTS":
    case "GUEST_AI_RATE_LIMITED":
    case "GUEST_METADATA_EDITOR_RATE_LIMITED":
    case "GUEST_BULK_ACTIVE_EXISTS":
      return 429;
    case "INVALID_REQUEST":
    case "UNSUPPORTED_MEDIA_TYPE":
    case "VALIDATION_FAILED":
    case "CORRUPT_IMAGE":
    case "OPERATION_NOT_SUPPORTED":
    case "GUEST_AI_RESPONSE_INVALID":
    case "GUEST_METADATA_EDITOR_DRAFT_INVALID":
    case "GUEST_METADATA_EDITOR_FIELD_TOO_LONG":
    case "GUEST_METADATA_EDITOR_FILENAME_INVALID":
    case "GUEST_METADATA_EDITOR_KEYWORDS_INVALID":
    case "GUEST_METADATA_EDITOR_AI_RESULT_NOT_ALLOWED":
    case "GUEST_BULK_LIMIT":
    case "GUEST_BULK_TOO_MANY_FILES":
    case "GUEST_BULK_BATCH_TOO_LARGE":
    case "GUEST_BULK_FEATURE_REQUIRED":
      return 400;
    case "OBJECT_NOT_FOUND":
    case "JOB_NOT_FOUND":
    case "GUEST_METADATA_EDITOR_AI_RESULT_NOT_FOUND":
    case "GUEST_METADATA_EDITOR_SOURCE_NOT_READY":
      return 404;
    case "JOB_NOT_READY":
    case "GUEST_METADATA_EDITOR_SOURCE_EXPIRED":
    case "GUEST_BULK_NOT_READY":
      return 409;
    case "STORAGE_NOT_CONFIGURED":
    case "GUEST_AI_NOT_CONFIGURED":
    case "GUEST_AI_PROVIDER_UNAVAILABLE":
    case "GUEST_AI_TIMEOUT":
    case "GUEST_METADATA_EDITOR_EXPORT_FAILED":
    case "GUEST_METADATA_EDITOR_RENAMED_DOWNLOAD_FAILED":
    case "GUEST_BULK_ZIP_FAILED":
    case "GUEST_BULK_ZIP_TOO_LARGE":
      return 503;
    default:
      return 500;
  }
}
