export {
  GUEST_GEOTAG_COORD_DECIMALS,
  GUEST_GEOTAG_COORD_TOLERANCE,
  GUEST_GEOTAG_METADATA_POLICY_VERSION,
  GUEST_GEOTAG_OPERATION,
  coordsWithinTolerance,
  decimalToDms,
  defaultGuestGeotagOptions,
  dmsToDecimal,
  guestGeotagOptionsEqual,
  isGuestGeotagJpegMime,
  parseGuestGeotagOptions,
  roundCoord,
  sanitizeLocationLabel,
  validateAltitude,
  validateLatitude,
  validateLongitude,
  type DecimalDms,
  type GuestGeotagOptions,
  type SafeGpsSummary,
} from "@/lib/guest/geotag-policy";
