export type SafeProcessingErrorCode =
  | "UNAUTHORIZED"
  | "INVALID_REQUEST"
  | "PROJECT_NOT_FOUND"
  | "IMAGE_NOT_FOUND"
  | "IMAGE_NOT_READY"
  | "PROCESSING_JOB_NOT_FOUND"
  | "PROCESSING_JOB_CONFLICT"
  | "PROCESSING_JOB_ALREADY_COMPLETED"
  | "PROCESSING_JOB_CANCELLED"
  | "PROCESSING_JOB_STALE"
  | "PROCESSING_RETRY_LIMIT_REACHED"
  | "SOURCE_OBJECT_MISSING"
  | "SOURCE_REVISION_CHANGED"
  | "SOURCE_FORMAT_UNSUPPORTED"
  | "SOURCE_ANIMATION_UNSUPPORTED"
  | "SOURCE_PIXEL_LIMIT_EXCEEDED"
  | "SOURCE_SIZE_LIMIT_EXCEEDED"
  | "SOURCE_DECODE_FAILED"
  | "PROCESSING_FAILED"
  | "CONVERSION_UNSUPPORTED"
  | "OUTPUT_SIZE_LIMIT_EXCEEDED"
  | "OUTPUT_UPLOAD_FAILED"
  | "OUTPUT_VERIFICATION_FAILED"
  | "OUTPUT_QUOTA_EXCEEDED"
  | "SUBSCRIPTION_RESTRICTED"
  | "PROCESSING_LIMIT_REACHED"
  | "FEATURE_NOT_INCLUDED"
  | "DERIVATIVE_CLEANUP_PENDING"
  | "DERIVATIVE_CLEANUP_FAILED"
  | "STORAGE_NOT_CONFIGURED"
  | "STORAGE_UNAVAILABLE";

export class ProcessingDomainError extends Error {
  readonly code: SafeProcessingErrorCode;

  constructor(code: SafeProcessingErrorCode, message?: string) {
    super(message ?? code);
    this.name = "ProcessingDomainError";
    this.code = code;
  }
}
